version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: {{SERVICE_NAME_SNAKE_CASE}}
    ports:
      - "54325:5432"
    volumes:
      - dbData:/var/lib/postgresql/data

volumes:
  dbData:
