apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: agnus
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: {{SERVICE_NAME}}
  sessionAffinity: None
  type: NodePort
